---
Logging:
  IncludeScopes: true
  LogLevel:
    Default: Information
    Steeltoe: Information
    Microsoft: Information
    FluentValidation: Warning
    System: Warning
    MediatR: Warning
ApiInfo:
  Title: SuperEats API
  Description: A template for ASP.NET Core Web API
  Contact:
    Name: PivotalServices
    Email: foo@bar.com
  License:
    Name: PivotalServices
    Url: https://licenses.bar.com/license1
  DeprecationMessage: " Warning: This API version has been deprecated."
management:
  endpoints:
    path: "/cloudfoundryapplication"
    cloudfoundry:
      validateCertificates: false
spring:
  application:
    name: SuperEats
  cloud:
    config:
      validate_certificates: false
      failFast: false
      name: SuperEats
      env: "${ASPNETCORE_ENVIRONMENT}"
eureka:
  client:
    validate_certificates: false
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true